/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dignote;

/**
 *
 * @author Ade Eki Nurhakim
 */
public class Kalkulator extends javax.swing.JFrame {
    String bil;
    double jumlah,bil1,bil2;
    int pilih;
    
    
    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        komaButton = new javax.swing.JButton();
        tambahButton = new javax.swing.JButton();
        nolButton = new javax.swing.JButton();
        duaButton = new javax.swing.JButton();
        satuButton = new javax.swing.JButton();
        tigaButton = new javax.swing.JButton();
        empatButton = new javax.swing.JButton();
        limaButton = new javax.swing.JButton();
        enamButton = new javax.swing.JButton();
        tujuhButton = new javax.swing.JButton();
        delapanButton = new javax.swing.JButton();
        sembilanButton = new javax.swing.JButton();
        samadenganButton = new javax.swing.JButton();
        kaliButton = new javax.swing.JButton();
        kurangButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        bagiButton = new javax.swing.JButton();
        txthasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        komaButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        komaButton.setText(",");
        komaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaButtonActionPerformed(evt);
            }
        });

        tambahButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tambahButton.setText("+");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        nolButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        nolButton.setText("0");
        nolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolButtonActionPerformed(evt);
            }
        });

        duaButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        duaButton.setText("2");
        duaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaButtonActionPerformed(evt);
            }
        });

        satuButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        satuButton.setText("1");
        satuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuButtonActionPerformed(evt);
            }
        });

        tigaButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tigaButton.setText("3");
        tigaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaButtonActionPerformed(evt);
            }
        });

        empatButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        empatButton.setText("4");
        empatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatButtonActionPerformed(evt);
            }
        });

        limaButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        limaButton.setText("5");
        limaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaButtonActionPerformed(evt);
            }
        });

        enamButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        enamButton.setText("6");
        enamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamButtonActionPerformed(evt);
            }
        });

        tujuhButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tujuhButton.setText("7");
        tujuhButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhButtonActionPerformed(evt);
            }
        });

        delapanButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        delapanButton.setText("8");
        delapanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanButtonActionPerformed(evt);
            }
        });

        sembilanButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        sembilanButton.setText("9");
        sembilanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanButtonActionPerformed(evt);
            }
        });

        samadenganButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        samadenganButton.setText("=");
        samadenganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganButtonActionPerformed(evt);
            }
        });

        kaliButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        kaliButton.setText("*");
        kaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliButtonActionPerformed(evt);
            }
        });

        kurangButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        kurangButton.setText("-");
        kurangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangButtonActionPerformed(evt);
            }
        });

        hapusButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        hapusButton.setText("C");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        bagiButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bagiButton.setText("/");
        bagiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiButtonActionPerformed(evt);
            }
        });

        txthasil.setEditable(false);
        txthasil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txthasil)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tujuhButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(delapanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(nolButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(satuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(duaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(empatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(limaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sembilanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enamButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tigaButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(komaButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bagiButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tambahButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(samadenganButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(kaliButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(kurangButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))))
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapusButton)
                    .addComponent(bagiButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delapanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tujuhButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sembilanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kaliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kurangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tigaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(komaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(samadenganButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(nolButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolButtonActionPerformed
        // TODO add your handling code here:
        bil +="0"; // nilai ganti dengan angka      
        txthasil.setText(bil); // menampilkan angka kedalam jTextField
    }//GEN-LAST:event_nolButtonActionPerformed

    private void komaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaButtonActionPerformed
        // TODO add your handling code here:
        bil +=","; // nilai ganti dengan angka      
        txthasil.setText(bil); // menampilkan angka kedalam jTextField
    }//GEN-LAST:event_komaButtonActionPerformed

    private void satuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuButtonActionPerformed
        // TODO add your handling code here:
        bil +="1"; // nilai ganti dengan angka      
        txthasil.setText(bil); // menampilkan angka kedalam jTextField
    }//GEN-LAST:event_satuButtonActionPerformed

    private void duaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaButtonActionPerformed
        // TODO add your handling code here:
        bil +="2"; // nilai ganti dengan angka      
        txthasil.setText(bil); // menampilkan angka kedalam jTextField
    }//GEN-LAST:event_duaButtonActionPerformed

    private void tigaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaButtonActionPerformed
        // TODO add your handling code here:
        bil +="3"; // nilai ganti dengan angka      
        txthasil.setText(bil); // menampilkan angka kedalam jTextField
    }//GEN-LAST:event_tigaButtonActionPerformed

    private void empatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatButtonActionPerformed
        // TODO add your handling code here:
        bil +="4"; // nilai ganti dengan angka      
        txthasil.setText(bil); // menampilkan angka kedalam jTextField
    }//GEN-LAST:event_empatButtonActionPerformed

    private void limaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaButtonActionPerformed
        // TODO add your handling code here:
        bil +="5"; // nilai ganti dengan angka      
        txthasil.setText(bil); // menampilkan angka kedalam jTextField
    }//GEN-LAST:event_limaButtonActionPerformed

    private void enamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamButtonActionPerformed
        // TODO add your handling code here:
        bil +="6"; // nilai ganti dengan angka      
        txthasil.setText(bil); // menampilkan angka kedalam jTextField
    }//GEN-LAST:event_enamButtonActionPerformed

    private void tujuhButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhButtonActionPerformed
        // TODO add your handling code here:
        bil +="7"; // nilai ganti dengan angka      
        txthasil.setText(bil); // menampilkan angka kedalam jTextField
    }//GEN-LAST:event_tujuhButtonActionPerformed

    private void delapanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanButtonActionPerformed
        // TODO add your handling code here:
        bil +="8"; // nilai ganti dengan angka      
        txthasil.setText(bil); // menampilkan angka kedalam jTextField
    }//GEN-LAST:event_delapanButtonActionPerformed

    private void sembilanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanButtonActionPerformed
        // TODO add your handling code here:
        bil +="9"; // nilai ganti dengan angka      
        txthasil.setText(bil); // menampilkan angka kedalam jTextField
    }//GEN-LAST:event_sembilanButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        txthasil.setText(null);
        bil1=0.0;
        bil2=0.0;
        jumlah=0.0;
        bil="";
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        // TODO add your handling code here:
        bil1 =Double.parseDouble(bil);
        txthasil.setText("+");
        bil="";
        pilih=1;  
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void kurangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangButtonActionPerformed
        // TODO add your handling code here:
        bil1 =Double.parseDouble(bil);
        txthasil.setText("-");
        bil="";
        pilih=2; 
    }//GEN-LAST:event_kurangButtonActionPerformed

    private void kaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliButtonActionPerformed
        // TODO add your handling code here:
        bil1 =Double.parseDouble(bil);
        txthasil.setText("*");
        bil="";
        pilih=3; 
    }//GEN-LAST:event_kaliButtonActionPerformed

    private void bagiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiButtonActionPerformed
        // TODO add your handling code here:
        bil1 =Double.parseDouble(bil);
        txthasil.setText("/");
        bil="";
        pilih=4; 
    }//GEN-LAST:event_bagiButtonActionPerformed

    private void samadenganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganButtonActionPerformed
        // TODO add your handling code here:
        switch(pilih){
        case 1:
            bil2 = Double.parseDouble(bil);
            jumlah = bil1 + bil2;
            bil = Double.toString(jumlah);
            txthasil.setText(bil);
            break;
        case 2:
            bil2 = Double.parseDouble(bil);
            jumlah = bil1 - bil2;
            bil = Double.toString(jumlah);
            txthasil.setText(bil);
            break;
        case 3:
            bil2 = Double.parseDouble(bil);
            jumlah = bil1 * bil2;
            bil = Double.toString(jumlah);
            txthasil.setText(bil);
            break;
        case 4:
            bil2 = Double.parseDouble(bil);
            jumlah = bil1 / bil2;
            bil = Double.toString(jumlah);
            txthasil.setText(bil);
            break;
            default:
            break;
    }
    }//GEN-LAST:event_samadenganButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagiButton;
    private javax.swing.JButton delapanButton;
    private javax.swing.JButton duaButton;
    private javax.swing.JButton empatButton;
    private javax.swing.JButton enamButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kaliButton;
    private javax.swing.JButton komaButton;
    private javax.swing.JButton kurangButton;
    private javax.swing.JButton limaButton;
    private javax.swing.JButton nolButton;
    private javax.swing.JButton samadenganButton;
    private javax.swing.JButton satuButton;
    private javax.swing.JButton sembilanButton;
    private javax.swing.JButton tambahButton;
    private javax.swing.JButton tigaButton;
    private javax.swing.JButton tujuhButton;
    private javax.swing.JTextField txthasil;
    // End of variables declaration//GEN-END:variables

        }